# Generated by Django 4.0.6 on 2022-07-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('editorial', models.CharField(max_length=30)),
                ('anio', models.DateField(null=True)),
            ],
        ),
    ]
