# Generated by Django 4.0.6 on 2022-07-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comic',
        ),
    ]
